### ISSUE TITLE
Write the full spelling of message tittle

### ISSUE THREAD

**Issue by mariach44** [usamach559/Passige#1]
Description:
The spelling of Message is not show proper that make confusion for user 

![e4ebb1eb-a327-4156-8ad2-a083815492d0](https://github.com/user-attachments/assets/d239ba18-3387-43e9-bad6-b796439c8afe)

**Comment by naveed21-m** [comment]
The spelling is according to the customer's requirement

**Comment by mariach44** [comment]
ok
